version: "3.2"
volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.0.0.4,rw,nolock
      device: ":/nfsexport/nginx-proxy-manager/letsencrypt"
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.0.0.4,rw,nolock
      device: ":/nfsexport/nginx-proxy-manager/app"
  nginx:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.0.0.4,rw,nolock
      device: ":/nfsexport/nginx-proxy-manager/nginx"
  mariadb-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.0.0.4,rw,nolock
      device: ":/nfsexport/nginx-proxy-manager/mariadb/config"
  mariadb-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.0.0.4,rw,nolock
      device: ":/nfsexport/nginx-proxy-manager/mariadb/data"
services:
  app:
    image: jc21/nginx-proxy-manager-base:latest-armhf 
    environment: 
      - FORCE_COLOR=1
    volumes:
      - letsencrypt:/etc/letsencrypt
      - app:/app
      - nginx:/etc/nginx
    working_dir: /app
    depends_on:
      - db
    links:
      - db
  db:
    image: lsioarmhf/mariadb:14.09.17
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - mariadb-config:/etc/mysql/conf.d/
      - mariadb-data:/var/lib/mysql
